# Generated by Django 2.0.9 on 2018-12-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gdansk',
            fields=[
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
                ('pm1', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gdynia',
            fields=[
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
                ('pm1', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grudziadz',
            fields=[
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
                ('pm1', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Katowice',
            fields=[
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
                ('pm1', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Krakow',
            fields=[
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
                ('pm1', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Krzeszowice',
            fields=[
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
                ('pm1', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenczynek',
            fields=[
                ('data', models.DateTimeField(primary_key=True, serialize=False)),
                ('pm1', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
